/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CounterComponent {}
  interface CounterComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'CounterComponent': Components.CounterComponent;
  }

  interface StencilIntrinsicElements {
    'counter-component': Components.CounterComponentAttributes;
  }


  interface HTMLCounterComponentElement extends Components.CounterComponent, HTMLStencilElement {}
  var HTMLCounterComponentElement: {
    prototype: HTMLCounterComponentElement;
    new (): HTMLCounterComponentElement;
  };

  interface HTMLElementTagNameMap {
    'counter-component': HTMLCounterComponentElement
  }

  interface ElementTagNameMap {
    'counter-component': HTMLCounterComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
